### ISSUE TITLE
Incomplete dataset link

### ISSUE THREAD

**Issue by Wangyi1121** [ZhangCYG/DDFHO#1]
You didn't provide a link to ShapeNetCore.v2, so I downloaded one from the internet myself. However, when trying to reproduce the code, the file directory path is incorrect.

**Comment by ZhangCYG** [comment]
ShapeNetCore.v2 can be downloaded using the official release. It is only used in the preprocess to generate DDF sampling, defined in 'preprocess/process_obman.py'. You could change the directory path using the argument '--shapenet_root', defined in Line 27, 28 in 'process_obman.py'. I hope it may help you.

**Comment by Wangyi1121** [comment]
![微信图片_20240326101403](https://github.com/ZhangCYG/DDFHO/assets/145657429/ed5d8219-a2d0-401f-a3f2-6bcaafa3d5d0)
Because the official website requires confirmation before being able to download the dataset, I downloaded a 2016 version from the internet. However, the file I obtained does not contain the specific file you mentioned in the original path. Now, do I just need to change the path to any models file under ShapeNetCore.v2? This is because I noticed that the images in that directory are unrelated to hand object reconstruction.

**Comment by ZhangCYG** [comment]
The process of DDFHO first needs the preprocess to generate DDF representation samplings for training and testing. In this data generation process, data from shapenetv2 is needed, since ObMan dataset is rendered by ShapeNet data. The generated data is indeed related to the hand-object images by ObMan annotations. If you have ensured that your --shapenet_root is correct, I would suggest you to download the dataset officially so that you can operate the data generation normally.

**Comment by Wangyi1121** [comment]
Hello, because the obman dataset requires approval from the official website before downloading, and I have been emailing them for several days without receiving permission. Do you happen to have a pre-downloaded obman dataset available?
![微信图片_20240329191240](https://github.com/ZhangCYG/DDFHO/assets/145657429/39e2da50-d0b3-4d41-998e-5a25eabff403)

**Comment by ZhangCYG** [comment]
According to the ObMan dataset license, it's improper to spread it privately without official permission. You could connect the ObMan author and wait their release. But I have another idea, that you can directly use the ObMan cache file provided by https://github.com/JudyYe/ihoi . For DDF preprocess using the cache data, you could modify the preprocess_obman.py similar with preprocess_ho3d.py, in which the annotated shapes are stored in the cache data of IHOI. I think this may help you.
