### ISSUE TITLE
Missed files in MOW dataset

### ISSUE THREAD

**Issue by lym29** [ZhangCYG/DDFHO#3]
Hi, thanks for sharing this wonderful work.

I noticed there are some files in a "results" folder mentioned within the [MOW dataset code](https://github.com/ZhangCYG/DDFHO/blob/7a09085678e6de92d46be5f38266be4848c8f804/datasets/mow.py#L50
), but I couldn't find them in the preprocessed data from IHOI. I am wondering about the purpose of these files and how I can obtain them. Could you please give some help?

Thanks!

**Comment by ZhangCYG** [comment]
This is just a intermediate directory for preprocess in the https://github.com/JudyYe/ihoi. We directly use the cache files from IHOI after this preprocess stage. It won't influence anything, just delete this line.

**Comment by lym29** [comment]
self.shape_dir = osp.join(self.data_dir, 'results/{0}/{0}_norm.obj')

Hi, I am wondering where to find meshes referenced in the above code.
To properly evaluate the reconstruction results, what preprocessing steps are required for the raw model data from the MOW dataset?
Thanks

**Comment by ZhangCYG** [comment]
For these intermediate files and folders, maybe you should contact authors of https://github.com/JudyYe/ihoi. DDFHO uses its dataloader. But note that these files are not necessary at all for training and testing for DDFHO. All files needed for evaluations are the cache files mentioned in the README.

**Comment by lym29** [comment]
> For these intermediate files and folders, maybe you should contact authors of https://github.com/JudyYe/ihoi. DDFHO uses its dataloader. But note that these files are not necessary at all for training and testing for DDFHO. All files needed for evaluations are the cache files mentioned in the README.

Ok I see, the gt object for computing CD is referred from [here](https://github.com/ZhangCYG/DDFHO/blob/a37e98cdf046c5eee83beb1e7424b609722e1871/models/ddfho.py#L203) right? Thank you for your patience.

**Comment by ZhangCYG** [comment]
If you look at the dataloader, you will find that the GT objects are read through "the cache file (https://drive.google.com/drive/folders/1v6Pw6vrOGIg6HUEHMVhAQsn-JLBWSHWu?usp=sharing). Unzip it and put under data/ folder."
